version: '3'

services:
    web:
        build: .
        container_name: web
        platform: linux/amd64
        env_file: .env
        restart: unless-stopped
        ports:
            - 8000:8000

        mem_limit: 128M

        logging:
            driver: json-file
            options:
                max-size: 10m

        healthcheck:
            test: curl -fs http://localhost:8000/health || exit 1
            interval: 2s
            timeout: 1s
            retries: 3
